name: auto

on:
  push:
    branches:
      - main  # 可以根据你的默认分支修改
  schedule:
    - cron: '0 5 15 * *'  # 每天的13:00 UTC时间

jobs:
  run_program:
    runs-on: ubuntu-latest  # 可以选择其他操作系统

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 选择你的 Python 版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有依赖，可以修改成你的依赖文件

    - name: Run Python Program
      run: python dome.py  # 修改成你的 Python 程序的文件名
