name: Generate Text File

on:
  push:
    branches:
      - main

jobs:
  generate_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run Python script
      run: python3 cesi2.py
      working-directory: ${{ github.workspace }}

    - name: Display directory contents
      run: ls -l
      working-directory: ${{ github.workspace }}
